"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { motion, useReducedMotion } from "motion/react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ArrowRight, Sparkles, Zap, ShieldCheck, MessageSquare, Heart } from "lucide-react";
import { Input } from "@/components/ui/Input";
import { Button } from "@/components/ui/Button";

// Google fonts imported via classes generated by next/font
import { DM_Sans } from "next/font/google";
import { Space_Grotesk } from "next/font/google";

const dm = DM_Sans({ subsets: ["latin"], weight: ["400", "500", "700"] });
const space = Space_Grotesk({ subsets: ["latin"], weight: ["400", "500", "600", "700"] });

gsap.registerPlugin(ScrollTrigger);

export default function LandingPage() {
  const router = useRouter();
  const heroRef = useRef<HTMLDivElement>(null);
  const pinRef = useRef<HTMLDivElement>(null);
  const reduce = useReducedMotion();

  useEffect(() => {
    if (reduce) return;
    const ctx = gsap.context(() => {
      if (heroRef.current) {
        gsap.from(heroRef.current, {
          y: 40,
          opacity: 0,
          duration: 1,
          ease: "power3.out",
          scrollTrigger: {
            trigger: heroRef.current,
            start: "top 60%",
            once: true,
          },
        });
      }
      if (pinRef.current) {
        ScrollTrigger.create({
          trigger: pinRef.current,
          start: "top top",
          end: "+=800",
          pin: true,
          pinSpacing: true,
        });
      }
    });
    return () => ctx.revert();
  }, [reduce]);

  const testimonials = [
    {
      name: "Maya R.",
      role: "Freelance Designer",
      quote:
        "ProposalPilot turned my notes into a client-ready proposal in 47 seconds. They signed same day.",
      avatar: "https://i.pravatar.cc/100?img=32",
    },
    {
      name: "Jon K.",
      role: "Consultant",
      quote:
        "Finally a tool that sounds like me, not a template. Tracking lets me follow up at the perfect time.",
      avatar: "https://i.pravatar.cc/100?img=12",
    },
    {
      name: "Aisha P.",
      role: "Agency Owner",
      quote:
        "We onboarded the whole team. Consistency and speed we didn't think possible.",
      avatar: "https://i.pravatar.cc/100?img=5",
    },
  ];

  return (
    <main
      className={`
        ${dm.className} min-h-screen bg-[#FAF5FF] text-[#0F172A] antialiased
        selection:bg-[#7C3AED]/20
      `}
    >
      <style jsx global>{`
        :root {
          --color-primary: #7C3AED;
          --color-accent: #EC4899;
          --color-bg: #FAF5FF;
          --color-fg: #0F172A;
          --color-muted: #475569;
          --color-border: #EFE7FC;
        }
        html { scroll-behavior: smooth; }
        @media (prefers-reduced-motion: reduce) {
          * {
            animation-duration: 0.01ms !important;
            transition-duration: 0.01ms !important;
          }
        }
      `}</style>

      <nav
        className="
          sticky top-0 z-40 backdrop-blur-xl bg-[#FAF5FF]/80 border-b border-[#EFE7FC]
        "
      >
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className={`${space.className} font-semibold tracking-tight text-lg`}>
            ProposalPilot
          </div>
          <button
            onClick={() => router.push("/dashboard")}
            className="
              cursor-pointer rounded-lg px-4 py-2 bg-[#7C3AED] text-white font-medium
              hover:opacity-90 active:opacity-80 transition-opacity duration-200
              focus:outline-none focus-visible:ring-2 focus-visible:ring-[#7C3AED]
            "
          >
            Open demo
          </button>
        </div>
      </nav>

      {/* Hero */}
      <section
        ref={heroRef}
        className="
          min-h-[100dvh] flex items-center py-32 md:py-48 relative overflow-x-hidden
        "
      >
        <div className="max-w-7xl mx-auto px-6 w-full grid lg:grid-cols-[1.1fr_0.9fr] gap-16 items-center">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-[#EFE7FC] bg-white px-3 py-1 text-sm">
              <Sparkles
                className="w-4 h-4 text-[#7C3AED]"
                aria-hidden="true"
              />
              <span>AI proposals in under a minute</span>
            </div>
            <h1
              className="
                max-w-6xl font-display text-[clamp(3rem,5vw,5.5rem)] leading-[0.95]
                tracking-tighter hero-title text-[#0F172A]
                ${space.className}
              "
            >
              Your next proposal in under a minute
            </h1>
            <p className="mt-6 text-lg text-[#475569] max-w-xl">
              Paste notes. Get a priced proposal that sounds like you. Track opens. No accounts needed.
            </p>
            <div className="mt-8 flex gap-3">
              <Button onClick={() => router.push("/dashboard")}>Open demo</Button>
              <Button variant="tertiary">See how it works</Button>
            </div>
          </div>
          <div className="scale-img opacity-80 scale-90 transition-transform">
            <img
              src="https://picsum.photos/seed/proposalpilot-hero/1200/900"
              alt="Proposal workspace"
              className="w-full rounded-2xl border border-[#8F92AB] shadow-2xl"
            />
          </div>
        </div>
      </section>

      {/* Problem */}
      <section className="py-32 md:py-48 bg-[#F5F5F5]">
        <div className="max-w-7xl mx-auto px-6">
          <h2 className="font-display text-3xl md:text-5xl tracking-tight text-[#0F172A]">
            Interest
          </h2>
          <div className="mt-10 grid grid-flow-dense grid-cols-12 gap-4 auto-rows-[180px]">
            <div className="col-span-12 lg:col-span-7 row-span-2 rounded-2xl overflow-hidden border border-[#EFE7FC] bg-white">
              <img
                src="https://picsum.photos/seed/bento1/1200/600"
                className="w-full h-full object-cover opacity-90"
                alt=""
              />
            </div>
            <div className="col-span-12 lg:col-span-5 rounded-2xl border border-[#EFE7FC] bg-white p-6">
              <p className="text-[#475569]">Learns your voice</p>
            </div>
            <div className="col-span-6 lg:col-span-3 rounded-2xl border border-[#EFE7FC] bg-white p-6">
              <p className="text-[#475569]">Pricing you can trust</p>
            </div>
            <div className="col-span-6 lg:col-span-3 rounded-2xl border border-[#EFE7FC] bg-white p-6">
              <p className="text-[#475569]">Tracking links</p>
            </div>
            <div className="col-span-12 lg:col-span-6 rounded-2xl border border-[#EFE7FC] bg-white p-6">
              <p className="text-[#475569]">Inline image in heading example</p>
            </div>
          </div>
        </div>
      </section>

      {/* Desire */}
      <section ref={pinRef} className="py-32 md:py-48">
        <div className="max-w-7xl mx-auto px-6 grid lg:grid-cols-2 gap-12">
          <div className="lg:sticky lg:top-24">
            <h2 className="font-display text-4xl tracking-tight text-[#0F172A]">
              Desire
            </h2>
            <p className="mt-4 text-[#475569]">Pinned title while content scrolls</p>
          </div>
          <div className="space-y-24">
            {[1, 2, 3].map((i) => (
              <div key={i} className="min-h-[60vh] flex items-center">
                <img
                  src={`https://picsum.photos/seed/desire${i}/1000/700`}
                  className="w-full rounded-2xl border border-[#8F92AB]"
                  alt=""
                />
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Action */}
      <section className="py-32 md:py-48 border-t border-[#EFE7FC]">
        <div className="max-w-7xl mx-auto px-6">
          <h2 className="font-display text-4xl tracking-tight text-[#0F172A]">
            Action
          </h2>
          <div className="mt-8 max-w-xl">
            <Input placeholder="you@example.com" />
            <Button className="mt-3">Get early access</Button>
          </div>
        </div>
      </section>

      <footer
        className="py-12 border-t border-[#EFE7FC] text-[#475569] text-sm"
      >
        <div className="max-w-7xl mx-auto px-6">
          Built by a freelancer for freelancers
        </div>
      </footer>
    </main>
  );
}